app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('auditoria/', include('audit.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='home'),
    path('contas_pagar/', include('contas_pagar.urls')),
    path('contas_receber/', include('contas_receber.urls')),
    path('empresas/', include('empresas.urls')),
    path('estoques/', include('estoques.urls')),
    path('dash/', include('dashes.urls')),
    path('dre/', include('dre.urls')),
    path('fornecedores/', include('fornecedores.urls')),
    path('usuarios/', include('usuarios.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

audit/urls.py
from django.urls import path

from .views import AuditoriasListView

urlpatterns = [
    path('', AuditoriasListView.as_view(), name='listar_auditorias'),
]

audit/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.models import MotivoExclusao


class Auditoria(models.Model):

    class Acao(models.TextChoices):
        CRIADO = "Criado", _("Criado")
        EDITADO = "Editado", _("Editado")
        EXCLUIDO = "Excluído", _("Excluído")

    tenant_id = models.UUIDField(db_index=True)
    acao = models.CharField(
        max_length=10, choices=Acao.choices,
        default=Acao.CRIADO, verbose_name="Ação"
    )
    motivo = models.ForeignKey(
        MotivoExclusao, on_delete=models.DO_NOTHING, verbose_name="Motivo"
    )
    registro = models.JSONField(verbose_name="Registro")
    usuario = models.CharField(max_length=100, verbose_name="Usuário")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Criado")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Atualizado")

    class Meta:
        db_table = "auditorias"
        verbose_name = "auditoria"
        verbose_name_plural = "Auditorias"

audit/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.views.generic import ListView

from core.models import MotivoExclusao

from .models import Auditoria


class AuditoriasListView(LoginRequiredMixin, ListView):
    model = Auditoria
    template_name = "audit/lista.html"
    paginate_by = 20

    def get_queryset(self):
        queryset = super().get_queryset().filter(
            tenant_id=self.request.user.userprofile.tenant_id
        )

        if "usuario" in self.request.GET and self.request.GET["usuario"]:
            queryset = queryset.filter(
                usuario=self.request.GET["usuario"]
            )
        if "motivo" in self.request.GET and self.request.GET["motivo"]:
            queryset = queryset.filter(
                motivo=self.request.GET["motivo"]
            )
        if "data_ini" in self.request.GET and self.request.GET["data_ini"]:
            queryset = queryset.filter(
                created_at__gte=self.request.GET["data_ini"]
            )
        if "data_end" in self.request.GET and self.request.GET["data_end"]:
            queryset = queryset.filter(
                created_at__lte=self.request.GET["data_end"]
            )
        if "acao" in self.request.GET and self.request.GET["acao"]:
            queryset = queryset.filter(
                acao=self.request.GET["acao"]
            )

        return queryset.order_by("-created_at")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["usuarios"] = User.objects.filter(
            userprofile__tenant_id=self.request.user.userprofile.tenant_id
        )
        context["motivos_exclusao"] = MotivoExclusao.objects.all()
        context["acoes"] = Auditoria.Acao.choices

        return context

audit/templates/audit/lista.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Auditorias</h1>
    </div>
    <form method="get" >
        <input type="hidden" name="page" value="{{ request.GET.page }}"/>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <div class="col-6 d-flex">
                    <div class="col-auto me-2">
                      <select name="acao" id="id_acao" class="form-select form-select-sm" aria-label="Default select example">
                        <option value="">Selecione Ação</option>
                        {% for acao in acoes %}
                          <option value="{{ acao.0 }}" {% if acao.0 == request.GET.acao %} selected {% endif %}>{{ acao.1 }}</option>
                        {% endfor %}
                      </select>
                    </div>
                    <div class="col-auto me-2">
                      <select name="usuario" id="id_usuario" class="form-select form-select-sm" aria-label="Default select example">
                        <option value="">Selecione Usuário</option>
                        {% for usuario in usuarios %}
                          <option value="{{ usuario.email }}" {% if usuario.email == request.GET.usuario %} selected {% endif %}>{{ usuario.email }}</option>
                        {% endfor %}
                      </select>
                    </div>
                    <div class="col-auto me-2">
                      <select name="motivo" id="id_motivo" class="form-select form-select-sm" aria-label="Default select example">
                        <option value="">Selecione Motivo</option>
                        {% for motivo in motivos_exclusao %}
                          <option value="{{ motivo.pk }}" {% if motivo.pk|stringformat:"s" == request.GET.motivo %} selected {% endif %}>{{ motivo.descricao }}</option>
                        {% endfor %}
                      </select>
                    </div>
                    <div class="col-auto me-2">
                        <label for="id_data_ini" class="col-form-label">Data:</label>
                    </div>
                    <div class="col-auto me-2">
                        <input name="data_ini" type="date" id="id_data_ini" class="form-control form-control-sm py-0" placeholder="Início" value="{{ request.GET.data_ini }}" />
                    </div>
                    <div class="col-auto me-2">
                        <label for="id_data_end" class="col-form-label">até</label>
                    </div>
                    <div class="col-auto me-2">
                        <input name="data_end" type="date" id="id_data_end" class="form-control form-control-sm py-0" placeholder="Fim"  value="{{ request.GET.data_end }}" />
                    </div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-sm btn-secondary">
                            <i class="bi bi-funnel-fill"></i> Filtrar
                        </button>
                    </div>
                </div>
            </div>
        </nav>
    </form>
    <div class="table-responsive small">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ação</th>
                    <th scope="col">Usuário</th>
                    <th scope="col">Motivo</th>
                    <th scope="col">Registro</th>
                    <th scope="col">Data</th>
                </tr>
            </thead>
            <tbody>
                {% for auditoria in page_obj %}
                    <tr>
                        <td>{{ auditoria.id }}</td>
                        <td>{{ auditoria.acao }}</td>
                        <td>{{ auditoria.usuario }}</td>
                        <td>{{ auditoria.motivo }}</td>
                        <td>{{ auditoria.registro|safe }}</td>
                        <td>{{ auditoria.created_at|date:'d/m/Y' }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        <nav aria-label="Page navigation example">
            <ul class="pagination pagination-sm justify-content-end">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">
                        <i class="bi bi-chevron-double-left"></i>
                    </a>
                </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <i class="bi bi-chevron-left"></i>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">
                            <i class="bi bi-chevron-double-left"></i>
                        </a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link">
                            <i class="bi bi-chevron-left"></i>
                        </a>
                    </li>
                {% endif %}
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                {% endif %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                    </li>
                {% endif %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <i class="bi bi-chevron-right"></i>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                            <i class="bi bi-chevron-double-right"></i>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">
                            <i class="bi bi-chevron-right"></i>
                        </a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link">
                            <i class="bi bi-chevron-double-right"></i>
                        </a>
                    </li>
                {% endif %}
                </li>
            </ul>
        </nav>
    </div>

{% endblock content %}