app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('auditoria/', include('audit.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='home'),
    path('contas_pagar/', include('contas_pagar.urls')),
    path('contas_receber/', include('contas_receber.urls')),
    path('empresas/', include('empresas.urls')),
    path('estoques/', include('estoques.urls')),
    path('dash/', include('dashes.urls')),
    path('dre/', include('dre.urls')),
    path('fornecedores/', include('fornecedores.urls')),
    path('usuarios/', include('usuarios.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contas_receber/urls.py
from django.urls import path

from .views import (ContasReceberCreateView, ContasReceberDeleteView,
                    ContasReceberListView, ContasReceberUpdateView,
                    delete_items)

urlpatterns = [
    path('', ContasReceberListView.as_view(), name='listar_contas_receber'),
    path(
        'add/', ContasReceberCreateView.as_view(),
        name='incluir_conta_receber'
    ),
    path(
        'edit/<int:pk>', ContasReceberUpdateView.as_view(),
        name='editar_conta_receber'
    ),
    path(
        'delete/<int:pk>', ContasReceberDeleteView.as_view(),
        name='deletar_conta_receber'
    ),
    path('delete-items', delete_items, name='deletar_items_conta_receber'),
]

contas_receber/models.py
from django.db import models

# Create your models here.

contas_receber/forms.py
from datetime import timedelta

from django import forms

from core.models import Banco, Categoria, CentroCusto, MotivoExclusao
from empresas.models import Empresa
from fluxo_caixa.models import FluxoCaixa
from fornecedores.models import Fornecedor


class ContaReceberForm(forms.ModelForm):

    class CategoriaChoiceField(forms.ModelChoiceField):

        def label_from_instance(self, obj):
            return f"{obj.descricao} | {obj.tipo_lancamento}"

    empresa = forms.ModelChoiceField(
        queryset=Empresa.objects.none(),
        label="Empresa"
    )
    fornecedor = forms.ModelChoiceField(
        queryset=Fornecedor.objects.none(),
        label="Fornecedor"
    )
    categoria = CategoriaChoiceField(
        queryset=Categoria.objects.all(),
        label="Categoria"
    )
    centro_custo = forms.ModelChoiceField(
        queryset=CentroCusto.objects.all(),
        required=False, label="Centro de Custo"
    )
    data_emissao = forms.DateField(
        widget=forms.DateInput(
            format="%d/%m/%Y", attrs={"type": "date", "max": ""}
        ),
        label="Data Emissão"
    )
    valor = forms.CharField(max_length=22, label="Valor Parcela")
    valor_moeda_estrangeira = forms.CharField(
        max_length=22, required=False, label="Moeda Estrangeira"
    )
    valor_cotacao = forms.CharField(
        max_length=6, required=False, label="Valor Cotação"
    )
    data_vencimento = forms.DateField(
        widget=forms.DateInput(format="%d/%m/%Y", attrs={"type": "date"}),
        label="Data Vencimento"
    )
    data_pagamento = forms.DateField(
        widget=forms.DateInput(format="%d/%m/%Y", attrs={"type": "date"}),
        required=False, label="Data Pagamento"
    )
    banco = forms.ModelChoiceField(
        queryset=Banco.objects.all().order_by("nome"),
        required=False, label="Banco"
    )
    projeto = forms.CharField(required=False, label="Projeto")
    forma_pagamento = forms.ChoiceField(
        choices=FluxoCaixa.FormasPagamentos.choices, label="Forma Pagamento"
    )
    num_documento = forms.CharField(required=False, label="Num. Documento")
    parcelas = forms.IntegerField(required=False, label="Parcelas")
    arquivo = forms.FileField(required=False, label="Arquivo")

    def __init__(self, *args, **kwargs):
        tenant_id = kwargs.pop("tenant_id")

        super().__init__(*args, **kwargs)

        self.fields["empresa"].queryset = Empresa.objects.filter(
            tenant_id=tenant_id
        )
        self.fields["fornecedor"].queryset = Fornecedor.objects.filter(
            tenant_id=tenant_id
        )

    def clean_valor(self):
        valor = self.cleaned_data["valor"]
        valor = valor.replace(".", "").replace(",", ".")

        return valor and float(valor)

    def clean_valor_moeda_estrangeira(self):
        valor_moeda_estrangeira = self.cleaned_data["valor_moeda_estrangeira"]

        if not valor_moeda_estrangeira:
            return None

        return valor_moeda_estrangeira

    def clean_valor_cotacao(self):
        valor_cotacao = self.cleaned_data["valor_cotacao"]

        if not valor_cotacao:
            return None

        return valor_cotacao

    def clean_parcelas(self):
        parcelas = self.cleaned_data["parcelas"]

        if not parcelas:
            return 1

        return parcelas

    def save(self, commit=True):
        parcelas = self.instance.parcelas

        instance = super().save(commit)
        parcela_pricipal_id = instance.pk

        for i in range(2, parcelas + 1):
            instance.pk = None
            instance.num_parcela = i
            instance.data_vencimento = instance.data_vencimento + timedelta(
                days=30
            )
            instance.parcela_principal = FluxoCaixa.objects.get(
                id=parcela_pricipal_id
            )
            instance.save()

        return instance

    class Meta:
        model = FluxoCaixa
        exclude = ["num_parcela", "parcela_principal"]


class ContaReceberUpdateForm(forms.ModelForm):

    class CategoriaChoiceField(forms.ModelChoiceField):

        def label_from_instance(self, obj):
            return f"{obj.descricao} | {obj.tipo_lancamento}"

    empresa = forms.ModelChoiceField(
        queryset=Empresa.objects.none(),
        label="Empresa", disabled=True
    )
    fornecedor = forms.ModelChoiceField(
        queryset=Fornecedor.objects.none(),
        label="Fornecedor", disabled=True
    )
    categoria = CategoriaChoiceField(
        queryset=Categoria.objects.all(),
        label="Categoria", disabled=True
    )
    centro_custo = forms.ModelChoiceField(
        queryset=CentroCusto.objects.all(),
        required=False, label="Centro de Custo", disabled=True
    )
    data_emissao = forms.DateField(
        widget=forms.DateInput(format="%d/%m/%Y", attrs={"type": "date"}),
        label="Data Emissão"
    )
    valor = forms.CharField(max_length=22, label="Valor")
    valor_moeda_estrangeira = forms.CharField(
        max_length=22, required=False, label="Moeda Estrangeira"
    )
    valor_cotacao = forms.CharField(
        max_length=6, required=False, label="Valor Cotação"
    )
    data_vencimento = forms.DateField(
        widget=forms.DateInput(format="%d/%m/%Y", attrs={"type": "date"}),
        label="Data Vencimento"
    )
    data_pagamento = forms.DateField(
        widget=forms.DateInput(format="%d/%m/%Y", attrs={"type": "date"}),
        required=False, label="Data Pagamento"
    )
    banco = forms.ModelChoiceField(
        queryset=Banco.objects.all().order_by("nome"),
        required=False, label="Banco"
    )
    projeto = forms.CharField(
        required=False, label="Projeto", disabled=True
    )
    forma_pagamento = forms.ChoiceField(
        choices=FluxoCaixa.FormasPagamentos.choices, label="Forma Pagamento"
    )
    num_documento = forms.CharField(required=False, label="Num. Documento")
    parcelas = forms.IntegerField(
        required=False, label="Parcelas", disabled=True
    )
    arquivo = forms.FileField(required=False, label="Arquivo")
    parcela_principal = forms.CharField(
        widget=forms.HiddenInput(), required=False
    )

    def clean_valor(self):
        valor = self.cleaned_data["valor"]
        valor = valor.replace(".", "").replace(",", ".")

        return valor and float(valor)

    def clean_valor_moeda_estrangeira(self):
        valor_moeda_estrangeira = self.cleaned_data["valor_moeda_estrangeira"]

        if not valor_moeda_estrangeira:
            return None

        return valor_moeda_estrangeira

    def clean_valor_cotacao(self):
        valor_cotacao = self.cleaned_data["valor_cotacao"]

        if not valor_cotacao:
            return None

        return valor_cotacao

    def clean_parcelas(self):
        parcelas = self.cleaned_data["parcelas"]

        if not parcelas:
            return 1

        return parcelas

    def clean_parcela_principal(self):
        parcela_principal = FluxoCaixa.objects.get(
            id=self.cleaned_data.get("parcela_principal")
        )
        return parcela_principal

    def __init__(self, *args, **kwargs):
        tenant_id = kwargs.pop("tenant_id")

        super().__init__(*args, **kwargs)

        self.fields["empresa"].queryset = Empresa.objects.filter(
            tenant_id=tenant_id
        )
        self.fields["fornecedor"].queryset = Fornecedor.objects.filter(
            tenant_id=tenant_id
        )

    class Meta:
        model = FluxoCaixa
        exclude = ["num_parcela"]


class ItemDeleteForm(forms.Form):
    motivo_exclusao = forms.ModelChoiceField(
        queryset=MotivoExclusao.objects.all()
    )
    items = forms.ModelMultipleChoiceField(
        queryset=FluxoCaixa.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )


class ContaReceberDeleteForm(forms.Form):
    motivo_exclusao = forms.ModelChoiceField(
        queryset=MotivoExclusao.objects.all()
    )

contas_receber/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core import serializers
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from audit.models import Auditoria
from core.models import Categoria, CentroCusto, MotivoExclusao
from empresas.models import Empresa
from fluxo_caixa.models import FluxoCaixa
from fornecedores.models import Fornecedor

from .forms import (ContaReceberDeleteForm, ContaReceberForm,
                    ContaReceberUpdateForm, ItemDeleteForm)


def delete_items(request):
    if request.method == "POST":
        form = ItemDeleteForm(request.POST)

        if form.is_valid():
            total = len(form.cleaned_data["items"])
            items_to_delete = form.cleaned_data["items"]

            for item in items_to_delete:
                item.deleted_at = datetime.now()
                item.save()

                user = request.user

                Auditoria(
                    tenant_id=user.userprofile.tenant_id,
                    acao=Auditoria.Acao.EXCLUIDO,
                    motivo=form.cleaned_data["motivo_exclusao"],
                    registro=serializers.serialize("json", [item]),
                    usuario=user.email
                ).save()

            messages.success(
                request, f"{total} contas a receber deletado com sucesso!"
            )
    else:
        form = ItemDeleteForm()

    return redirect("listar_contas_receber")  # Redirect after deletion


class ContasReceberListView(LoginRequiredMixin, ListView):
    model = FluxoCaixa
    template_name = "contas_receber/lista.html"
    paginate_by = 20

    def get_queryset(self):
        queryset = super().get_queryset().filter(
            Q(empresa__tenant_id=self.request.user.userprofile.tenant_id),
            Q(deleted_at=None),
            Q(valor__gt=0) | Q(valor_moeda_estrangeira__gt=0)
        )

        if "empresa" in self.request.GET and self.request.GET["empresa"]:
            queryset = queryset.filter(
                empresa=self.request.GET["empresa"]
            )
        if "fornecedor" in self.request.GET and self.request.GET["fornecedor"]:
            queryset = queryset.filter(
                fornecedor=self.request.GET["fornecedor"]
            )
        if "categoria" in self.request.GET and self.request.GET["categoria"]:
            queryset = queryset.filter(
                categoria=self.request.GET["categoria"]
            )
        if (
            "centro_custo" in self.request.GET
            and self.request.GET["centro_custo"]
        ):
            queryset = queryset.filter(
                centro_custo=self.request.GET["centro_custo"]
            )
        if (
            "data_vencimento_ini" in self.request.GET
            and self.request.GET["data_vencimento_ini"]
        ):
            queryset = queryset.filter(
                data_vencimento__gte=self.request.GET["data_vencimento_ini"]
            )
        if (
            "data_vencimento_end" in self.request.GET
            and self.request.GET["data_vencimento_end"]
        ):
            queryset = queryset.filter(
                data_vencimento__lte=self.request.GET["data_vencimento_end"]
            )
        if "projeto" in self.request.GET and self.request.GET["projeto"]:
            queryset = queryset.filter(
                projeto__icontains=self.request.GET["projeto"]
            )

        return queryset.order_by("data_vencimento")

    def get(self, request, *args, **kwargs):
        kwargs['tenant_id'] = request.user.userprofile.tenant_id

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["categorias"] = Categoria.objects.all()
        context["centro_custos"] = CentroCusto.objects.all()
        context["motivos_exclusao"] = MotivoExclusao.objects.all()
        context["empresas"] = Empresa.objects.filter(
            tenant_id=self.request.user.userprofile.tenant_id
        )
        context["fornecedores"] = Fornecedor.objects.filter(
            tenant_id=self.request.user.userprofile.tenant_id
        )

        return context


class ContasReceberCreateView(
    LoginRequiredMixin, SuccessMessageMixin, CreateView
):
    form_class = ContaReceberForm
    template_name = "contas_receber/form.html"
    success_url = reverse_lazy("listar_contas_receber")
    success_message = "Conta a receber criada com sucesso."

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['tenant_id'] = self.request.user.userprofile.tenant_id

        return kwargs


class ContasReceberUpdateView(
    LoginRequiredMixin, SuccessMessageMixin, UpdateView
):
    model = FluxoCaixa
    form_class = ContaReceberUpdateForm
    template_name = "contas_receber/form.html"
    success_url = reverse_lazy("listar_contas_receber")
    success_message = "Conta a receber atualizada com sucesso."

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['tenant_id'] = self.request.user.userprofile.tenant_id

        return kwargs


class ContasReceberDeleteView(
    LoginRequiredMixin, SuccessMessageMixin, DeleteView
):
    model = FluxoCaixa
    form_class = ContaReceberDeleteForm
    template_name = "contas_receber/confirmar_exclusao.html"
    success_url = reverse_lazy("listar_contas_receber")
    success_message = "Conta a receber deletada com sucesso."

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.deleted_at = datetime.now()
        self.object.save()

        user = self.request.user

        Auditoria(
            tenant_id=user.userprofile.tenant_id,
            acao=Auditoria.Acao.EXCLUIDO,
            motivo=form.cleaned_data["motivo_exclusao"],
            registro=serializers.serialize("json", [self.object]),
            usuario=user.email
        ).save()

        return HttpResponseRedirect(success_url)

contas_receber/templates/contas_receber/confirmar_exclusao.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Excluir Conta Receber</h1>
</div>

<div class="continer">
    <div class="row">
        <div class="col-md-6">
            <form class="row g-1" method="post">
                {% csrf_token %}
                <p>Você confirma a exclusão da conta a receber "{{ object }}"?</p>
                {{ form|crispy }}
                
                <div class="d-flex flex-row-reverse py-2">
                    <button type="submit" class="btn btn-primary ms-2">Salvar</button>
                    <a href="{% url 'listar_contas_receber' %}" class="btn btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

contas_receber/templates/contas_receber/form.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Cadastro Conta Receber</h1>
    </div>

    <div class="continer">
        <div class="row">
            <div class="col-md-8">
                <form class="row g-2" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% if form.parcela_principal %}
                        {{ form.parcela_principal|as_crispy_field }}
                    {% endif %}
                    <div class="col-md-8">
                        {{ form.empresa|as_crispy_field }}
                    </div>
                    <div class="col-md-3">
                        {{ form.data_emissao|as_crispy_field }}
                    </div>
                    <div class="col-md-8">
                        {{ form.fornecedor|as_crispy_field }}
                    </div>
                    <div class="col-md-5">
                        {{ form.categoria|as_crispy_field }}
                    </div>
                    <div class="col-md-5">
                        {{ form.centro_custo|as_crispy_field }}
                    </div>
                    <div class="col-md-3">
                        {{ form.valor|as_crispy_field }}
                    </div>
                    <div class="col-md-3">
                        {{ form.valor_moeda_estrangeira|as_crispy_field }}
                    </div>
                    <div class="col-md-3">
                        {{ form.valor_cotacao|as_crispy_field }}
                    </div>
                    <div class="col-md-3">
                        {{ form.data_vencimento|as_crispy_field }}
                    </div>
                    <div class="col-md-3">
                        {{ form.data_pagamento|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.banco|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.projeto|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.forma_pagamento|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.num_documento|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.parcelas|as_crispy_field }}
                    </div>
                    <div class="col-md-8">
                        {{ form.arquivo|as_crispy_field }}
                    </div>
                    <div class="d-flex flex-row-reverse py-2">
                        <button type="submit" class="btn btn-primary ms-2">Salvar</button>
                        <a href="{% url 'listar_contas_receber' %}" class="btn btn-secondary">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock content %}

{% block js %}
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>

    <script>
        $(document).ready(function () {
            const today = new Date().toISOString().split("T")[0];
            $('#id_data_emissao').attr('max', today);

            $('#id_valor').mask('000.000.000.000.000,00', {reverse: true});
            $('#id_valor_moeda_estrangeira').mask('000,000,000,000,000.00', {reverse: true});
            $('#id_valor_cotacao').mask('000.00', {reverse: true});

            const data_emissao = $('#id_data_emissao').attr('value');

            if(data_emissao) {
                $('#id_data_emissao').attr('value', data_emissao.replace(/(\d{2})\/(\d{2})\/(\d{4})/g,'$3-$2-$1'));
            }

            const data_vencimento = $('#id_data_vencimento').attr('value');

            if(data_vencimento) {
                $('#id_data_vencimento').attr('value', data_vencimento.replace(/(\d{2})\/(\d{2})\/(\d{4})/g,'$3-$2-$1'));
            }

            const data_pagamento = $('#id_data_pagamento').attr('value');

            if(data_pagamento) {
                $('#id_data_pagamento').attr('value', data_pagamento.replace(/(\d{2})\/(\d{2})\/(\d{4})/g,'$3-$2-$1'));
            }
        });
    </script>
{% endblock %}