app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('auditoria/', include('audit.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='home'),
    path('contas_pagar/', include('contas_pagar.urls')),
    path('contas_receber/', include('contas_receber.urls')),
    path('empresas/', include('empresas.urls')),
    path('estoques/', include('estoques.urls')),
    path('dash/', include('dashes.urls')),
    path('dre/', include('dre.urls')),
    path('fornecedores/', include('fornecedores.urls')),
    path('usuarios/', include('usuarios.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

empresas/urls.py
from django.urls import path

from .views import (EmpresasCreateView, EmpresasDeleteView, EmpresasListView,
                    EmpresasUpdateView)

urlpatterns = [
    path('', EmpresasListView.as_view(), name='listar_empresas'),
    path('add/', EmpresasCreateView.as_view(), name='incluir_empresa'),
    path('edit/<int:pk>', EmpresasUpdateView.as_view(), name='editar_empresa'),
    path(
        'delete/<int:pk>',
        EmpresasDeleteView.as_view(), name='deletar_empresa'
    ),
]

empresas/models.py
from django.db import models

from main.models import Estados


class Empresa(models.Model):
    tenant_id = models.UUIDField(db_index=True)
    nome = models.CharField(max_length=50, verbose_name="Nome")
    cnpj = models.CharField(
        max_length=18, unique=True, verbose_name="CNPJ"
    )
    nome_razao_social = models.CharField(
        max_length=100, unique=True, verbose_name="Razão Social"
    )
    im = models.CharField(
        max_length=10, null=True, blank=True, verbose_name="Insc. Municipal"
    )
    ie = models.CharField(
        max_length=10, null=True, blank=True, verbose_name="Insc. Estadual"
    )
    telefone = models.CharField(
        max_length=14, null=True, blank=True, verbose_name="Telefone"
    )
    whatsapp = models.CharField(
        max_length=15, null=True, blank=True, verbose_name="Whatsapp"
    )
    email = models.CharField(
        max_length=80, null=True, blank=True, verbose_name="E-mail"
    )
    cep = models.CharField(
        max_length=9, null=True, blank=True, verbose_name="Cep"
    )
    endereco = models.CharField(
        max_length=60, null=True, blank=True, verbose_name="Endereço"
    )
    complemento = models.CharField(
        max_length=60, null=True, blank=True, verbose_name="Complemento"
    )
    numero = models.CharField(
        max_length=5, null=True, blank=True, verbose_name="Número"
    )
    bairro = models.CharField(
        max_length=80, null=True, blank=True, verbose_name="Bairro"
    )
    estado = models.CharField(
        max_length=80, null=True, blank=True,
        choices=Estados.choices, verbose_name="Estado"
    )
    cidade = models.CharField(
        max_length=80, null=True, blank=True, verbose_name="Cidade"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Criado")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Atualizado")

    def __str__(self):
        return self.nome

    class Meta:
        db_table = "empresas"
        verbose_name = "empresa"
        verbose_name_plural = "empresas"
        constraints = [
            models.UniqueConstraint(fields=["tenant_id", "cnpj"], name="unique_empresa_tenant") # noqa
        ]

empresas/forms.py
from django import forms

from .models import Empresa


class EmpresaForm(forms.ModelForm):

    def save(self, commit=True):
        if 'tenant_id' in self.initial:
            self.instance.tenant_id = self.initial['tenant_id']

        return super().save(commit)

    class Meta:
        model = Empresa
        fields = [
            'nome', 'nome_razao_social', 'cnpj', 'im', 'ie', 'telefone',
            'whatsapp', 'email', 'cep', 'endereco', 'numero', 'complemento',
            'bairro', 'estado', 'cidade',
        ]

empresas/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import EmpresaForm
from .models import Empresa


class EmpresasListView(LoginRequiredMixin, ListView):
    model = Empresa
    paginate_by = 20
    template_name = "empresas/lista.html"

    def get_queryset(self):
        return super().get_queryset().filter(
            tenant_id=self.request.user.userprofile.tenant_id
        ).order_by("-created_at")


class EmpresasCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = EmpresaForm
    template_name = "empresas/form.html"
    success_url = reverse_lazy("listar_empresas")
    success_message = "Empresa cadastrada com sucesso."

    def post(self, request, *args, **kwargs):
        self.initial["tenant_id"] = request.user.userprofile.tenant_id

        return super().post(request, *args, **kwargs)


class EmpresasUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Empresa
    form_class = EmpresaForm
    template_name = "empresas/form.html"
    success_url = reverse_lazy("listar_empresas")
    success_message = "Empresa atualizado com sucesso."


class EmpresasDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Empresa
    template_name = "empresas/confirmar_exclusao.html"
    success_url = reverse_lazy("listar_empresas")
    success_message = "Empresa deletado com sucesso."

empresas/templates/empresas/confirmar_exclusao.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Excluir Empresa</h1>
</div>

<div class="continer">
    <div class="row">
        <div class="col-md-6">
            <form class="row g-1" method="post">
                {% csrf_token %}
                <p>Você confirma a exclusão da empresa "{{ object }}"?</p>
                {{ form|crispy }}
                
                <div class="d-flex flex-row-reverse py-2">
                    <button type="submit" class="btn btn-primary ms-2">Salvar</button>
                    <a href="{% url 'listar_empresas' %}" class="btn btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

empresas/templates/empresas/form.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Cadastro Empresa</h1>
    </div>

    <div class="continer">
        <div class="row">
            <div class="col-md-8">
                <form class="row g-2" method="post">
                    {% csrf_token %}
                    <div class="col-md-8">
                        {{ form.nome|as_crispy_field }}
                    </div>
                    <div class="col-md-8">
                        {{ form.nome_razao_social|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.cnpj|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.ie|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.im|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.telefone|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.whatsapp|as_crispy_field }}
                    </div>
                    <div class="col-md-8">
                        {{ form.email|as_crispy_field }}
                    </div>
                    <div class="col-md-8">
                        {{ form.endereco|as_crispy_field }}
                    </div>
                    <div class="col-md-2">
                        {{ form.numero|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.complemento|as_crispy_field }}
                    </div>
                    <div class="col-md-5">
                        {{ form.bairro|as_crispy_field }}
                    </div>
                    <div class="col-md-5">
                        {{ form.cidade|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.estado|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.cep|as_crispy_field }}
                    </div>
                    <div class="d-flex flex-row-reverse py-2">
                        <button type="submit" class="btn btn-primary ms-2">Salvar</button>
                        <a href="{% url 'listar_empresas' %}" class="btn btn-secondary">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock content %}

{% block js %}
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>

    <script>
        $(document).ready(function  () {
            $('#id_cnpj').mask('00.000.000/0000-00');
            $('#id_telefone').mask('(00) 0000-0000');
            $('#id_whatsapp').mask('(00) 00000-0000');
            $('#id_cep').mask('00000-000');
        });
    </script>
{% endblock %}

empresas/templates/empresas/lista.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Empresas</h1>
    </div>
    <div class="d-flex justify-content-end">
        <a class="btn btn-primary btn-sm" href="{% url 'incluir_empresa' %}">
            <i class="bi bi-plus"></i> Incluir
        </a>
    </div>
    <div class="table-responsive small">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">CNPJ</th>
                    <th scope="col">Razão</th>
                    <th scope="col">Insc. Municipal</th>
                    <th scope="col">Insc. Estadual</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">Whatsapp</th>
                    <th scope="col">Cidade</th>
                    <th scope="col">Estado</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for empresa in page_obj %}
                    <tr>
                        <td>{{ empresa.id }}</td>
                        <td>{{ empresa.nome }}</td>
                        <td>{{ empresa.cnpj }}</td>
                        <td>{{ empresa.nome_razao_social }}</td>
                        <td>{{ empresa.im }}</td>
                        <td>{{ empresa.ie }}</td>
                        <td>{{ empresa.telefone }}</td>
                        <td>{{ empresa.whatsapp }}</td>
                        <td>{{ empresa.cidade }}</td>
                        <td>{{ empresa.estado }}</td>
                        <td>
                            <a class="btn btn-outline-secondary btn-sm" href="{% url 'editar_empresa' empresa.pk %}">
                                <i class="bi bi-pencil-fill"></i>
                            </a>
                            <a class="btn btn-outline-danger btn-sm" href="{% url 'deletar_empresa' empresa.pk %}">
                                <i class="bi bi-trash2-fill"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <nav aria-label="Page navigation example">
            <ul class="pagination pagination-sm justify-content-end">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">
                        <i class="bi bi-chevron-double-left"></i>
                    </a>
                </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <i class="bi bi-chevron-left"></i>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">
                            <i class="bi bi-chevron-double-left"></i>
                        </a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link">
                            <i class="bi bi-chevron-left"></i>
                        </a>
                    </li>
                {% endif %}
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                {% endif %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                    </li>
                {% endif %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <i class="bi bi-chevron-right"></i>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                            <i class="bi bi-chevron-double-right"></i>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">
                            <i class="bi bi-chevron-right"></i>
                        </a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link">
                            <i class="bi bi-chevron-double-right"></i>
                        </a>
                    </li>
                {% endif %}
                </li>
            </ul>
        </nav>
    </div>
    
    <div class="modal fade" id="cadEmpresa" tabindex="-1" aria-labelledby="cadEmpresaLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-body">
                    <p>Modal body text goes here.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                    <button type="button" class="btn btn-primary">Salvar</button>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}