app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('auditoria/', include('audit.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='home'),
    path('contas_pagar/', include('contas_pagar.urls')),
    path('contas_receber/', include('contas_receber.urls')),
    path('empresas/', include('empresas.urls')),
    path('estoques/', include('estoques.urls')),
    path('dash/', include('dashes.urls')),
    path('dre/', include('dre.urls')),
    path('fornecedores/', include('fornecedores.urls')),
    path('usuarios/', include('usuarios.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

fornecedores/urls.py
from django.urls import path

from .views import (FornecedoresCreateView, FornecedoresDeleteView,
                    FornecedoresListView, FornecedoresUpdateView)

urlpatterns = [
    path('', FornecedoresListView.as_view(), name='listar_fornecedores'),
    path('add/', FornecedoresCreateView.as_view(), name='incluir_fornecedor'),
    path(
        'edit/<int:pk>',
        FornecedoresUpdateView.as_view(),
        name='editar_fornecedor'
    ),
    path(
        'delete/<int:pk>',
        FornecedoresDeleteView.as_view(),
        name='deletar_fornecedor'
    ),
]

fornecedores/models.py
from django.db import models

from main.models import Estados


class Fornecedor(models.Model):
    tenant_id = models.UUIDField(db_index=True)
    nome = models.CharField(max_length=50, verbose_name="Nome")
    cpf_cnpj = models.CharField(
        max_length=18, null=True, blank=True, verbose_name="CPF/CNPJ"
    )
    nome_razao_social = models.CharField(
        max_length=100, null=True, blank=True, verbose_name="Razão social"
    )
    im = models.CharField(
        max_length=10, null=True, blank=True, verbose_name="Insc. Municipal"
    )
    ie = models.CharField(
        max_length=10, null=True, blank=True, verbose_name="Insc. Estadual"
    )
    telefone = models.CharField(
        max_length=15, null=True, blank=True, verbose_name="Telefone"
    )
    whatsapp = models.CharField(
        max_length=15, null=True, blank=True, verbose_name="Whatsapp"
    )
    email = models.CharField(
        max_length=80, null=True, blank=True, verbose_name="E-mail"
    )
    cep = models.CharField(
        max_length=9, null=True, blank=True, verbose_name="Cep"
    )
    endereco = models.CharField(
        max_length=60, null=True, blank=True, verbose_name="Endereço"
    )
    complemento = models.CharField(
        max_length=60, null=True, blank=True, verbose_name="Complemento"
    )
    numero = models.CharField(
        max_length=5, null=True, blank=True, verbose_name="Número"
    )
    bairro = models.CharField(
        max_length=80, null=True, blank=True, verbose_name="Bairro"
    )
    estado = models.CharField(
        max_length=80, null=True, blank=True,
        choices=Estados.choices, verbose_name="Estado"
    )
    cidade = models.CharField(
        max_length=80, null=True, blank=True, verbose_name="Cidade"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Criado")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Atualizado")

    def __str__(self):
        return self.nome

    class Meta:
        db_table = "fornecedores"
        verbose_name = "fornecedores"
        verbose_name_plural = "fornecedores"

fornecedores/forms.py
from django import forms

from .models import Fornecedor


class FornecedorForm(forms.ModelForm):

    def save(self, commit=True):
        if 'tenant_id' in self.initial:
            self.instance.tenant_id = self.initial['tenant_id']

        return super().save(commit)

    class Meta:
        model = Fornecedor
        fields = [
            'nome', 'nome_razao_social', 'cpf_cnpj', 'im', 'ie', 'telefone',
            'whatsapp', 'email', 'cep', 'endereco', 'numero', 'complemento',
            'bairro', 'estado', 'cidade',
        ]

fornecedores/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import FornecedorForm
from .models import Fornecedor


class FornecedoresListView(LoginRequiredMixin, ListView):
    model = Fornecedor
    paginate_by = 20
    template_name = "fornecedores/lista.html"

    def get_queryset(self):
        return super().get_queryset().filter(
            tenant_id=self.request.user.userprofile.tenant_id
        ).order_by("-created_at")


class FornecedoresCreateView(
    LoginRequiredMixin, SuccessMessageMixin, CreateView
):
    form_class = FornecedorForm
    template_name = "fornecedores/form.html"
    success_url = reverse_lazy("listar_fornecedores")
    success_message = "Fornecedor cadastradp com sucesso."

    def post(self, request, *args, **kwargs):
        self.initial["tenant_id"] = request.user.userprofile.tenant_id

        return super().post(request, *args, **kwargs)


class FornecedoresUpdateView(
    LoginRequiredMixin, SuccessMessageMixin, UpdateView
):
    model = Fornecedor
    form_class = FornecedorForm
    template_name = "fornecedores/form.html"
    success_url = reverse_lazy("listar_fornecedores")
    success_message = "Fornecedor atualizado com sucesso."


class FornecedoresDeleteView(
    LoginRequiredMixin, SuccessMessageMixin, DeleteView
):
    model = Fornecedor
    template_name = "fornecedores/confirmar_exclusao.html"
    success_url = reverse_lazy("listar_fornecedores")
    success_message = "Fornecedor deletado com sucesso."

fornecedores/templates/fornecedores/confirmar_exclusao.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Excluir Fornecedor</h1>
</div>

<div class="continer">
    <div class="row">
        <div class="col-md-6">
            <form class="row g-1" method="post">
                {% csrf_token %}
                <p>Você confirma a exclusão do fornecedor "{{ object }}"?</p>
                {{ form|crispy }}
                
                <div class="d-flex flex-row-reverse py-2">
                    <button type="submit" class="btn btn-primary ms-2">Salvar</button>
                    <a href="{% url 'listar_fornecedores' %}" class="btn btn-secondary">Cancelar</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

fornecedores/templates/fornecedores/form.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Cadastro Fornecedores</h1>
    </div>

    <div class="continer">
        <div class="row">
            <div class="col-md-8">
                <form class="row g-2" method="post">
                    {% csrf_token %}
                    <div class="col-md-8">
                        {{ form.nome|as_crispy_field }}
                    </div>
                    <div class="col-md-8">
                        {{ form.nome_razao_social|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.cpf_cnpj|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.ie|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.im|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.telefone|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.whatsapp|as_crispy_field }}
                    </div>
                    <div class="col-md-8">
                        {{ form.email|as_crispy_field }}
                    </div>
                    <div class="col-md-8">
                        {{ form.endereco|as_crispy_field }}
                    </div>
                    <div class="col-md-2">
                        {{ form.numero|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.complemento|as_crispy_field }}
                    </div>
                    <div class="col-md-5">
                        {{ form.bairro|as_crispy_field }}
                    </div>
                    <div class="col-md-5">
                        {{ form.cidade|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.estado|as_crispy_field }}
                    </div>
                    <div class="col-md-4">
                        {{ form.cep|as_crispy_field }}
                    </div>
                    <div class="d-flex flex-row-reverse py-2">
                        <button type="submit" class="btn btn-primary ms-2">Salvar</button>
                        <a href="{% url 'listar_fornecedores' %}" class="btn btn-secondary">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock content %}

{% block js %}
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>

    <script>
        var cpfCnpjOptions = {
                onKeyPress: function(val, e, field, options) {
                    const masks = ['000.000.000-00', '00.000.000/0000-00'];
                    let mask = val.replace(/\D/g, '').length === 14 ? masks[1] : masks[0];
                    $('#id_cpf_cnpj').mask(mask, options);
                }
            };
        $(document).ready(function  () {
            $('#id_cpf_cnpj').mask('000.000.000-00', cpfCnpjOptions);
            $('#id_telefone').mask('(00) 0000-0000');
            $('#id_whatsapp').mask('(00) 00000-0000');
            $('#id_cep').mask('00000-000');
        });
    </script>
{% endblock %}

fornecedores/templates/fornecedores/lista.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Fornecedores</h1>
    </div>
    <div class="d-flex justify-content-end">
        <a class="btn btn-primary btn-sm" href="{% url 'incluir_fornecedor' %}">
            <i class="bi bi-plus"></i> Incluir
        </a>
    </div>
    <div class="table-responsive small">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">CNPJ</th>
                    <th scope="col">Razão</th>
                    <th scope="col">Insc. Municipal</th>
                    <th scope="col">Insc. Estadual</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">Whatsapp</th>
                    <th scope="col">Cidade</th>
                    <th scope="col">Estado</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for fornecedor in page_obj %}
                    <tr>
                        <td>{{ fornecedor.id }}</td>
                        <td>{{ fornecedor.nome }}</td>
                        <td>{{ fornecedor.cnpj }}</td>
                        <td>{{ fornecedor.nome_razao_social }}</td>
                        <td>{{ fornecedor.im|default:"-" }}</td>
                        <td>{{ fornecedor.ie|default:"-" }}</td>
                        <td>{{ fornecedor.telefone }}</td>
                        <td>{{ fornecedor.whatsapp }}</td>
                        <td>{{ fornecedor.cidade }}</td>
                        <td>{{ fornecedor.estado }}</td>
                        <td>
                            <a class="btn btn-outline-secondary btn-sm" href="{% url 'editar_fornecedor' fornecedor.pk %}">
                                <i class="bi bi-pencil-fill"></i>
                            </a>
                            <a class="btn btn-outline-danger btn-sm" href="{% url 'deletar_fornecedor' fornecedor.pk %}">
                                <i class="bi bi-trash2-fill"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <nav aria-label="Page navigation example">
            <ul class="pagination pagination-sm justify-content-end">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">
                        <i class="bi bi-chevron-double-left"></i>
                    </a>
                </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <i class="bi bi-chevron-left"></i>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">
                            <i class="bi bi-chevron-double-left"></i>
                        </a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link">
                            <i class="bi bi-chevron-left"></i>
                        </a>
                    </li>
                {% endif %}
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                {% endif %}
                <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                    </li>
                {% endif %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <i class="bi bi-chevron-right"></i>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                            <i class="bi bi-chevron-double-right"></i>
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">
                            <i class="bi bi-chevron-right"></i>
                        </a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link">
                            <i class="bi bi-chevron-double-right"></i>
                        </a>
                    </li>
                {% endif %}
                </li>
            </ul>
        </nav>
    </div>

{% endblock content %}